<?php
if ( ! defined( 'ABSPATH' ) ) exit;
if ( $role !== 'admin' ) { echo '<p class="text-danger">Access denied.</p>'; return; }
global $wpdb;
$accounts = $wpdb->get_results( "SELECT a.*, COALESCE(SUM(e.debit),0) debit_total, COALESCE(SUM(e.credit),0) credit_total FROM {$wpdb->prefix}rp_ledger_accounts a LEFT JOIN {$wpdb->prefix}rp_ledger_entries e ON e.account_id=a.id GROUP BY a.id ORDER BY a.name" );
$entries = $wpdb->get_results( "SELECT e.*,a.name account_name,a.account_type FROM {$wpdb->prefix}rp_ledger_entries e INNER JOIN {$wpdb->prefix}rp_ledger_accounts a ON a.id=e.account_id ORDER BY e.entry_date DESC,e.id DESC LIMIT 100" );
$salaries = $wpdb->get_results( "SELECT * FROM {$wpdb->prefix}rp_salary_records ORDER BY salary_month DESC,id DESC LIMIT 100" );
$staff = get_users( [ 'role__in' => [ 'rp_manager','rp_cashier','rp_kitchen_staff','rp_waiter','administrator' ], 'orderby' => 'display_name' ] );
$total_due = 0; foreach ( $accounts as $a ) $total_due += (float)$a->opening_balance + (float)$a->debit_total - (float)$a->credit_total;
$salary_due = (float)$wpdb->get_var( "SELECT COALESCE(SUM(due_amount),0) FROM {$wpdb->prefix}rp_salary_records" );
?>
<div class="flex-between mb-16"><h1 class="page-title" style="margin-bottom:0">Accounts & Ledgers</h1><span class="text-sm text-muted">Customers • Parties • Salary • Other</span></div>
<div class="stat-grid">
 <div class="stat-card red"><div class="stat-icon">📒</div><div class="stat-value">Rs.<?php echo number_format($total_due,0); ?></div><div class="stat-label">Net Ledger Balance</div></div>
 <div class="stat-card gold"><div class="stat-icon">👥</div><div class="stat-value"><?php echo count($accounts); ?></div><div class="stat-label">Ledger Accounts</div></div>
 <div class="stat-card green"><div class="stat-icon">💼</div><div class="stat-value">Rs.<?php echo number_format($salary_due,0); ?></div><div class="stat-label">Salary Due</div></div>
</div>
<div style="display:grid;grid-template-columns:repeat(auto-fit,minmax(290px,1fr));gap:16px">
 <div class="p-card"><h3 class="p-card-title mb-12">Add Ledger Account</h3><form method="post"><?php wp_nonce_field('rp_accounts_action'); ?><input type="hidden" name="rp_account_action" value="add_account"><div class="form-group"><label class="form-label">Type</label><select name="account_type" class="form-select"><option value="customer">Customer</option><option value="party">Party / Supplier</option><option value="staff">Staff</option><option value="other">Other</option></select></div><div class="form-group"><label class="form-label">Name</label><input name="name" class="form-input" required></div><div class="form-group"><label class="form-label">Phone</label><input name="phone" class="form-input"></div><div class="form-group"><label class="form-label">Email</label><input name="email" type="email" class="form-input"></div><div class="form-group"><label class="form-label">Address</label><input name="address" class="form-input"></div><div class="form-group"><label class="form-label">Opening Balance (Debit + / Credit -)</label><input name="opening_balance" type="number" step="0.01" class="form-input" value="0"></div><div class="form-group"><label class="form-label">Notes</label><textarea name="notes" class="form-input"></textarea></div><button class="btn btn-primary" type="submit">Save Account</button></form></div>
 <div class="p-card"><h3 class="p-card-title mb-12">Add Ledger Entry</h3><form method="post"><?php wp_nonce_field('rp_accounts_action'); ?><input type="hidden" name="rp_account_action" value="add_entry"><div class="form-group"><label class="form-label">Account</label><select name="account_id" class="form-select" required><option value="">Select</option><?php foreach($accounts as $a): ?><option value="<?php echo (int)$a->id; ?>"><?php echo esc_html($a->name.' — '.ucfirst($a->account_type)); ?></option><?php endforeach; ?></select></div><div class="form-group"><label class="form-label">Date</label><input name="entry_date" type="date" class="form-input" value="<?php echo esc_attr(current_time('Y-m-d')); ?>"></div><div class="form-group"><label class="form-label">Type</label><select name="entry_type" class="form-select"><option value="sale">Sale / Receivable</option><option value="payment">Payment Received</option><option value="purchase">Purchase / Payable</option><option value="expense">Expense</option><option value="advance">Advance</option><option value="general">General</option></select></div><div class="form-group"><label class="form-label">Reference</label><input name="reference" class="form-input" placeholder="Invoice / voucher"></div><div class="form-group"><label class="form-label">Description</label><input name="description" class="form-input"></div><div style="display:grid;grid-template-columns:1fr 1fr;gap:10px"><div class="form-group"><label class="form-label">Debit</label><input name="debit" type="number" step="0.01" class="form-input" value="0"></div><div class="form-group"><label class="form-label">Credit</label><input name="credit" type="number" step="0.01" class="form-input" value="0"></div></div><button class="btn btn-primary" type="submit">Add Entry</button></form></div>
 <div class="p-card"><h3 class="p-card-title mb-12">Salary Record</h3><form method="post"><?php wp_nonce_field('rp_accounts_action'); ?><input type="hidden" name="rp_account_action" value="add_salary"><div class="form-group"><label class="form-label">Staff</label><select name="staff_user_id" class="form-select" id="salaryStaff"><option value="0" data-name="">Manual / Other</option><?php foreach($staff as $u): ?><option value="<?php echo (int)$u->ID; ?>" data-name="<?php echo esc_attr($u->display_name); ?>"><?php echo esc_html($u->display_name); ?></option><?php endforeach; ?></select><input name="staff_name" id="salaryStaffName" class="form-input mt-8" placeholder="Staff name" required></div><div class="form-group"><label class="form-label">Month</label><input name="salary_month" type="month" class="form-input" value="<?php echo esc_attr(current_time('Y-m')); ?>"></div><div style="display:grid;grid-template-columns:1fr 1fr;gap:10px"><div class="form-group"><label class="form-label">Base Salary</label><input name="base_salary" type="number" step="0.01" class="form-input" value="0"></div><div class="form-group"><label class="form-label">Bonus</label><input name="bonus" type="number" step="0.01" class="form-input" value="0"></div><div class="form-group"><label class="form-label">Deduction</label><input name="deduction" type="number" step="0.01" class="form-input" value="0"></div><div class="form-group"><label class="form-label">Amount Paid</label><input name="amount_paid" type="number" step="0.01" class="form-input" value="0"></div></div><div class="form-group"><label class="form-label">Notes</label><textarea name="notes" class="form-input"></textarea></div><button class="btn btn-primary" type="submit">Save Salary</button></form></div>
</div>
<div class="p-card mt-16"><div class="p-card-header"><h3 class="p-card-title">Ledger Balances</h3></div><?php if($accounts): foreach($accounts as $a): $bal=(float)$a->opening_balance+(float)$a->debit_total-(float)$a->credit_total; ?><div class="order-item"><span class="order-num"><?php echo esc_html(ucfirst($a->account_type)); ?></span><div class="order-meta"><strong><?php echo esc_html($a->name); ?></strong><span class="text-sm text-muted"><?php echo esc_html($a->phone); ?></span></div><span class="order-total" style="color:<?php echo $bal>0?'#dc2626':'#16a34a'; ?>">Rs.<?php echo number_format(abs($bal),2); ?> <?php echo $bal>0?'Dr':'Cr'; ?></span></div><?php endforeach; else: ?><div class="empty-state"><p>No ledger accounts yet.</p></div><?php endif; ?></div>
<div class="p-card mt-16"><div class="p-card-header"><h3 class="p-card-title">Recent Ledger Entries</h3></div><?php if($entries): foreach($entries as $e): ?><div class="order-item"><span class="order-num"><?php echo esc_html(wp_date('d M',strtotime($e->entry_date))); ?></span><div class="order-meta"><strong><?php echo esc_html($e->account_name); ?></strong><span class="text-sm text-muted"><?php echo esc_html($e->description ?: $e->entry_type); ?> <?php echo $e->reference?'• '.esc_html($e->reference):''; ?></span></div><span class="order-total">Dr <?php echo number_format((float)$e->debit,0); ?> / Cr <?php echo number_format((float)$e->credit,0); ?></span></div><?php endforeach; else: ?><div class="empty-state"><p>No entries yet.</p></div><?php endif; ?></div>
<div class="p-card mt-16"><div class="p-card-header"><h3 class="p-card-title">Salary History</h3></div><?php if($salaries): foreach($salaries as $s): ?><div class="order-item"><span class="order-num"><?php echo esc_html($s->salary_month); ?></span><div class="order-meta"><strong><?php echo esc_html($s->staff_name); ?></strong><span class="text-sm text-muted">Net Rs.<?php echo number_format((float)$s->net_salary,0); ?> • Paid Rs.<?php echo number_format((float)$s->amount_paid,0); ?></span></div><span class="badge badge-<?php echo $s->status==='paid'?'completed':'new'; ?>"><?php echo esc_html(ucfirst($s->status)); ?> • Due Rs.<?php echo number_format((float)$s->due_amount,0); ?></span></div><?php endforeach; else: ?><div class="empty-state"><p>No salary records yet.</p></div><?php endif; ?></div>
<script>document.getElementById('salaryStaff')?.addEventListener('change',function(){var o=this.options[this.selectedIndex];if(o&&o.dataset.name)document.getElementById('salaryStaffName').value=o.dataset.name;});</script>
