(function(){'use strict';
document.querySelectorAll('[style*="e8f5e9"]').forEach(function(el){setTimeout(function(){el.style.display='none';},3000);});
var wrap=document.querySelector('.rp-notification-wrap'),bell=document.getElementById('rpNotificationBell'),panel=document.getElementById('rpNotificationPanel'),list=document.getElementById('rpNotificationList'),badge=document.getElementById('rpNotificationBadge'),audioCtx=null,audioPlayer=document.getElementById('rpNotificationSound');
if(!wrap||!bell||!panel||!list)return; var cfg=window.RPNotifications||{},ajaxUrl=cfg.ajaxUrl||'',nonce=cfg.nonce||'',key='rp_notification_cursor_v1',cursor=parseInt(localStorage.getItem(key)||'0',10)||0,unread=0,boot=cursor>0,busy=false;
function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,function(c){return{'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c];});}
function tm(v){var d=new Date(String(v).replace(' ','T'));return isNaN(d)?v:d.toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'});}
function icon(t){var m={payment:'dollar-sign',kitchen:'flame',order_kot:'flame',status:'activity',table:'layout',reservation:'calendar',message:'message',new_order:'receipt'};return '<span class=\"rp-icon-glyph rp-icon-'+(m[t]||'bell')+'\"></span>';}
function add(ev){if(!ev)return;try{document.dispatchEvent(new CustomEvent('rp:notification',{detail:ev}));}catch(e){}var row=document.createElement('div');row.className='rp-notification-item';var link=ev.order_id?cfg.panelUrl+'/orders/'+ev.order_id:'';row.innerHTML='<div class="rp-notification-icon">'+icon(ev.event_type)+'</div><div class="rp-notification-copy"><strong>'+esc(ev.title)+'</strong><div>'+esc(ev.message)+'</div><div class="rp-notification-foot"><small>'+esc(tm(ev.created_at))+'</small>'+(link?'<a href="'+esc(link)+'">View order</a>':'')+'</div></div>';var empty=list.querySelector('.rp-notification-empty');if(empty)empty.remove();list.insertBefore(row,list.firstChild);while(list.children.length>30)list.removeChild(list.lastChild);}
function badgeUpdate(){badge.textContent=unread>99?'99+':unread;badge.style.display=unread?'flex':'none';if(unread){wrap.classList.add('has-unread');bell.classList.remove('is-read');}else if(!panel.classList.contains('open')){wrap.classList.remove('has-unread');bell.classList.remove('is-read');}else{wrap.classList.add('has-unread');bell.classList.add('is-read');}}
function unlockAudio(){try{var C=window.AudioContext||window.webkitAudioContext;if(!audioCtx&&C)audioCtx=new C();if(audioCtx&&audioCtx.state==='suspended')audioCtx.resume();}catch(e){}}function alertDevice(ev){unread++;badgeUpdate();try{if('Notification'in window&&Notification.permission==='granted')new Notification(ev.title,{body:ev.message,tag:'rp-'+ev.id,requireInteraction:false});}catch(e){}try{unlockAudio();if(audioPlayer){audioPlayer.currentTime=0;var p=audioPlayer.play();if(p&&p.catch)p.catch(function(){});}}catch(e){}}
function permission(){if('Notification'in window&&Notification.permission==='default'){try{Notification.requestPermission();}catch(e){}}}
function poll(){if(busy||!ajaxUrl)return;busy=true;var b=new URLSearchParams();b.append('action','rp_notifications_poll');b.append('nonce',nonce);b.append('after_id',cursor);fetch(ajaxUrl,{method:'POST',credentials:'same-origin',body:b}).then(function(r){return r.json();}).then(function(res){if(!res||!res.success)return;var ev=res.data.events||[];if(!boot){ev.forEach(add);cursor=parseInt(res.data.newest_id||cursor,10)||cursor;localStorage.setItem(key,cursor);boot=true;return;}ev.forEach(function(e){add(e);cursor=Math.max(cursor,parseInt(e.id,10)||0);alertDevice(e);});if(ev.length)localStorage.setItem(key,cursor);}).catch(function(){}).finally(function(){busy=false;});}
document.addEventListener('pointerdown',unlockAudio,{once:true});bell.addEventListener('click',function(e){e.stopPropagation();panel.classList.toggle('open');if(panel.classList.contains('open')){unread=0;badgeUpdate();permission();}});document.addEventListener('click',function(e){if(!panel.contains(e.target)&&!bell.contains(e.target)){panel.classList.remove('open');badgeUpdate();}});poll();setInterval(poll,4000);
})();
